### ISSUE TITLE
Update Library for Release-Ready

### ISSUE THREAD

**Issue by gregLibert** [massalabs/massa-as-sdk#165]
# Objective
The purpose of this issue is to ensure that the library is updated to meet the expected criteria for an application to be maintained and considered release-ready. The requirements are outlined in the Run team procedure: [Definition of Release-Ready](https://www.notion.so/massa-innoteam/Definition-of-Release-Ready-964a4f2ffd9549129edf76d6c623c490).

# Tasks
This issue is a meta issue. Please create additional issues to perform the task and reference them. Keep in mind that the issues should be as short as possible to improve overall efficiency.
## Testing

- [x] #166
- [x] #168
- [x] #170
- [x] #171

## Documentation

- [x] #173
- [x] #175
- [x]  [Add code samples to Massa in Action](https://github.com/massalabs/hackathons/pull/11)
- [x] #176

## Security

- [ ]  Define a security model
- [ ]  Implement proper countermeasures, such as static analysis of code and security checks of dependencies

## Automation

- [x]  Automate tasks that can be automated

## Wrap Up

- [ ]  Ensure that the Run team procedure was properly applied and update the document if necessary
- [ ]  Communicate that the library is now considered release-ready

**Comment by Ben-Rey** [comment]
About Massa In action we should first make it ready imo

**Comment by gregLibert** [comment]
let's put massa in action on hold for now. the security part will be done in a second time.
