### ISSUE TITLE
 organize and explain organization

### ISSUE THREAD

**Issue by gregLibert** [massalabs/massa-as-sdk#190]
This package is a mess, we should:

in a not destructive way (duplicate and use deprecated tag)

 ## Organize the functions ...
... in consistent modules

- [x] #253
- [x] #242
- [x] #222 - extract execution functions into dedicated modules 

## Rename functions ...
... based on there usage, not necessarly how it works under the hood on the rust side and with simpler terms.

- [ ] #252

## Document all that

- [x] #257
- [x] for each module
- [x] update the tsdoc dedicated readme file

**Comment by 0xSwapFeeder** [comment]
#222 Aim's to tackle the module organization part.

**Comment by gregLibert** [comment]
> #222 Aim's to tackle the module organization part.

Can you update the initial issue instead ? Check the boxes that are covered and for each line check, add a trailing `- #<issue number>` to let the reader know wher we are on this subject

**Comment by gregLibert** [comment]
@Ben-Rey can we close this ?
