### ISSUE TITLE
Title: Create Mock for `assembly_script_is_address_eoa` in `vm.js`

### ISSUE THREAD

**Issue by Ben-Rey** [massalabs/massa-as-sdk#332]
## Description

We need to create a mock for the `assembly_script_is_address_eoa` function in the `vm.js` file. This will allow us to write unit tests that don't rely on the actual implementation of this function.

## Tasks

- [ ] Create a mock for `assembly_script_is_address_eoa`
- [ ] Update unit tests to use the mock
- [ ] Ensure all tests pass with the mock
